resources/src/test/java/org/hl7/davinci/cdshooks/medicationprescribe/MedicationPrescribeRequestTest.java
resources/src/test/resources/org/hl7/davinci/cdshooks/medicationprescribe/request.json
server/src/main/java/endpoint/cdshooks/services/crd/MedicationPrescribeService.java
server/src/main/java/endpoint/cdshooks/services/crd/OrderReviewService.java
server/src/main/java/endpoint/controllers/CdsHooksController.java
server/src/test/java/endpoint/cdshooks/services/crd/OrderReviewServiceTest.java
testingClient/src/main/java/TestClient.java

Both endpoints still need to be hooked up to the database layer.
NOTE: The URL for the order-review endpoint has changed to make room for
the new medication-prescribe hook.

Implemented endpoint for medication-prescribe

---

request-generator/src/components/DropdownInput.js
request-generator/src/containers/RequestBuilder.js
server/src/main/java/org/hl7/davinci/endpoint/database/CoverageRequirementRule.java
server/src/main/resources/db/sample_data.csv
server/src/main/resources/db/setup_db.sql
server/src/main/resources/templates/rules-table.html
server/src/test/java/ServerTest.java

Codes belong to code systems. We have sample data that belongs to both
CPT and HCPCS. This change adds a column to the database to store the
code system. Updates the sample data with the correct code system. It
updates the CoverageRequirementRule model and the web UI. It also
updates the request-generator so that values there now have a code
system and that value is no longer hard coded to HCPCS.
Note that this is a work in progress. The CDS services do not yet check code systems and the finder does not support searching by it. I'm waiting until @daco101 is done making changes in the finder code to make that update.

Adding a code_system column to the database

---

resources/src/main/java/org/hl7/davinci/CrdRequestCreator.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderReviewService.java

This PR changes the request creator to use hapi references instead of reference strings so that these generated requests will work when passed in to the services (currently they will work if converted to json/xml and then parsed back into the service, but not if directly passed in as objects). 
It also reverts orderreviewservice to use linked resources only.

request creator reference fix and orderreviewservice revert

---

server/build.gradle
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/MedicationPrescribeService.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderReviewService.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/stu3/MedicationPrescribeService.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/stu3/OrderReviewService.java
server/src/main/java/org/hl7/davinci/endpoint/components/CardBuilder.java

If the services reach the end of their processing, but the code in the
service has not added any cards, a warning card will be generated
stating that the request didn't have enough information. This typically
happens when the patient is null (broken reference) or it can't find a
CodeableConcept in the passed in request resource.
This also removes the spring devtools which was causing the server to
reload on each request.

Warning card and remove devtools

---

ehr-server/src/main/resources/data/5. patient.json
resources/src/main/java/org/hl7/davinci/FatalRequestIncompleteException.java
resources/src/main/java/org/hl7/davinci/r4/crdhook/CrdPrefetchTemplateElements.java
server/src/main/java/org/hl7/davinci/endpoint/components/PrefetchHydrator.java
server/src/test/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/EndToEndRequestPrefetchTest.java
server/src/test/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderReviewServiceTest.java

This PR modifies the hydrator so it will throw an error (which is returned to the client with status 400) if there are resources without id's which we need, and also to throw an error if we need to do a prefetch but there is no fhir server provided.

Resource id check

---

request-generator/src/components/App.js
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
server/src/main/java/org/hl7/davinci/endpoint/database/CoverageRequirementRule.java
server/src/main/request_logging/src/components/HealthInfo.js
server/src/main/resources/templates/data.html
server/src/main/resources/templates/rules-table.html

this adds the state info to the data table, which is displayed at `/data` and `/` on the server, and the request log.   The request generator already supports states from a previous PR.  
This also changes the request generators title from "React App" to "Request Generator".

Add states to ui

---

ehr-server/src/main/java/org/hl7/davinci/ehrserver/ClientAuthorizationInterceptor.java
ehr-server/src/main/java/org/hl7/davinci/ehrserver/EhrServer.java
ehr-server/src/main/java/org/hl7/davinci/ehrserver/FhirServerConfig.java
ehr-server/src/main/java/org/hl7/davinci/ehrserver/ServerConformance.java
ehr-server/src/main/resources/fhirServer.properties
ehr-server/src/main/webapp/WEB-INF/web.xml
resources/src/main/java/org/hl7/davinci/PatientInfo.java
resources/src/main/java/org/hl7/davinci/r4/Utilities.java
resources/src/main/java/org/hl7/davinci/stu3/Utilities.java
server/src/main/java/org/hl7/davinci/endpoint/YamlConfig.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
server/src/main/java/org/hl7/davinci/endpoint/components/CardBuilder.java
server/src/main/java/org/hl7/davinci/endpoint/database/CoverageRequirementRuleCriteria.java
server/src/main/resources/application.yml
server/src/test/java/org/hl7/davinci/endpoint/cdshooks/components/CardBuilderTest.java

This PR adds a link to the cards returned to the request generator which launches the smart on FHIR app.  The DTR app needs to be running for it to work.  To test it you can switch the ID of the patient on the incoming request from the request generator (or directly make a request to one of the service endpoints and follow the link returned in the JSON and choose some patient ID) to some patient that exists in the EHR server.  The program will fail currently if the patient does not have a name, which most of the sample patients do not have. 
The app launch will trigger a chain of auth events, first acquiring the token and authorization keycloak endpoints from the fhir server conformance statement.  The token and authorization endpoints can be set in `fhirServer.properties` in the …

Smart app cards

---

server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java

The PR tweaks the smart url builder to return a patient id and fhir server url that are ready to use by the js smart client.

fix smart url builder for patientid

---

server/README.md
server/src/main/resources/node_interfaces/buildout.sh
server/src/main/resources/node_interfaces/package.json

Added a `buildx` command to the `node_interfaces` subproject which automatically moves the built out files into the correct folder so that they are used by the server when it is run.  Running `npm run buildx` or `npm run-script buildx` will build out `node_interfaces`, delete the old static files in the server's `static` folder, rename the built out .css and .js files, and move them to the proper directory.

added build command to update node_interfaces

---

resources/src/main/java/org/hl7/davinci/r4/Utilities.java
server/src/main/java/org/hl7/davinci/endpoint/YamlConfig.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/MedicationPrescribeService.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderReviewService.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/stu3/MedicationPrescribeService.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/stu3/OrderReviewService.java
server/src/main/java/org/hl7/davinci/endpoint/components/CardBuilder.java
server/src/main/resources/application.yml

This creates a link in the card detail (which we don't show) which is clickable on the words `documentation requirements`.  If Epic's system is like the CDS hooks sandbox, they will be using react markdown, which accepts links in the `[text](link)` format.
Also creates a setting in the servers `application.yml` that can make practitioner location optional.  When `checkPractitionerLocation` is set to true, the program will throw an error is no location is found.  If it is set to false, the program will still search for cards with or without a practitioner location.  If there is no location provided, rules requiring practitioner location are ignored.

[DME196, DME197] Connectathon changes

---

server/README.md
server/src/main/resources/node_interfaces/public/index.html
server/src/main/resources/node_interfaces/src/App.js
server/src/main/resources/node_interfaces/src/components/requestLog/request.css
server/src/main/resources/node_interfaces/src/containers/RequestLog.css
server/src/main/resources/node_interfaces/src/containers/RequestLog.js

Fixes the little page number buttons on the request log.  It now only shows 9 pages at a time, and there are little arrow buttons that you can use to scroll through the pages.
Also fixed inconsistent button sizing and centering.
Testing might be a bit difficult since you need to run the server version.  I haven't included the static files in this PR since the structure of the static files gets changed in my other PR #102 and they will have to be rebuilt anyway (and also my react scripts was installed globally and now builds it the new way so I can't get the old static scripts to even upload here)
If you want to test it, run `buildout.sh` first and then run the server.  You'll have to make over 150 requests to see the new changes in action, or you can change `entriesPerPage` at the top of …

[213] Request log pages

---

server/src/main/jib/smartAppFhirArtifacts/home-oxygen-questionnaire.json

Didn't actually require any change to the cql, since the FHIR was written correctly.  Gender is a `code` type, not `coding`, meaning it's taken from a specific valueset as defined by the spec, in this case the `administrativeGender` valueSet.  The code for the choice input in the questionnaire builder in the DTR app was changed instead to deal with codes that might not come with a specified system, but an implied system.  Of course, that implied value set still needs to get passed to the contained resources of the questionnaire resource somehow.  
So really all this is doing is aligning the codes between the questionnaires value set and the administrativeGender value set.

[266] changed codes in the questionnaire for change to admin codes

---

server/src/main/jib/smartAppFhirArtifacts/BasicPatientInfoPrepopulate.cql
server/src/main/jib/smartAppFhirArtifacts/OxygenTherapyPrepopulation.cql
server/src/main/jib/smartAppFhirArtifacts/PositiveAirwayPressurePrepopulate.cql
server/src/main/jib/smartAppFhirArtifacts/home-oxygen-questionnaire_2.json
server/src/main/jib/smartAppFhirArtifacts/library-basic-patient-info-prepopulate.json
server/src/main/jib/smartAppFhirArtifacts/library-oxygen-therapy-prepopulate.json
server/src/main/jib/smartAppFhirArtifacts/positive-airway-pressure-questionnaire.json
server/src/main/jib/smartAppFhirArtifacts/valueset-copd.json

- Moved basic patient info out of the two existing pre-population libraries
- Created shared BasicPatientInfo library
- Made both questionnaires reference the basic patient info library
- Updated CQL result references in questionnaires to reference library name and statement name
- Started ValueSet refactor by moving COPD codes in OxygenTherapy to an "expanded" FHIR ValueSet.
- Added dataRequirement to the oxygen therapy library to reference the ValueSet

Initial pass at refactoring DTR CQL. Multiple libraries and value sets

---

resources/src/main/java/org/cdshooks/Hook.java
resources/src/main/java/org/hl7/davinci/r4/crdhook/CrdPrefetch.java
resources/src/main/java/org/hl7/davinci/r4/crdhook/CrdPrefetchTemplateElements.java
resources/src/main/java/org/hl7/davinci/r4/crdhook/orderselect/OrderSelectContext.java
resources/src/main/java/org/hl7/davinci/r4/crdhook/orderselect/OrderSelectRequest.java
resources/src/main/java/org/hl7/davinci/stu3/crdhook/CrdPrefetch.java
resources/src/main/java/org/hl7/davinci/stu3/crdhook/CrdPrefetchTemplateElements.java
resources/src/main/java/org/hl7/davinci/stu3/crdhook/orderselect/OrderSelectContext.java
resources/src/main/java/org/hl7/davinci/stu3/crdhook/orderselect/OrderSelectRequest.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderSelectService.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/stu3/OrderSelectService.java
server/src/main/java/org/hl7/davinci/endpoint/controllers/r4/CdsHooksController.java
server/src/main/java/org/hl7/davinci/endpoint/controllers/stu3/CdsHooksController.java

The order-select hook will work for STU3 and R4. The selections field in the hook is ignored and all of the contained DeviceRequests are processed.

[435] Add order-select hook to CRD - Connectathon

---

server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
server/src/main/jib/smartAppFhirArtifacts/library-oxygen-therapy-prepopulate.json

There's a change to the name of a file in the library for CQL retrieval, that might break things.  DMEERX-636 addresses this.  It's not imperative that we keep or remove the change, but it won't work with Epic's implementation without this change given the nature of the "bug".

Connectathon 2020

---

server/src/main/java/org/hl7/davinci/endpoint/YamlConfig.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
server/src/main/resources/application.yml

The test-ehr does not work with a url encoded app context. This change puts the encoding on a config switch until a workaround for the test-ehr can be found.

Add a configuration switch to enable url encoding of the app context.

---

server/src/main/java/org/hl7/davinci/endpoint/controllers/DataController.java
server/src/main/java/org/hl7/davinci/endpoint/database/FhirResource.java
server/src/main/java/org/hl7/davinci/endpoint/database/FhirResourceCriteria.java
server/src/main/java/org/hl7/davinci/endpoint/database/FhirResourceRepository.java
server/src/main/java/org/hl7/davinci/endpoint/files/CommonFileStore.java
server/src/main/java/org/hl7/davinci/endpoint/files/FhirResourceProcessor.java
server/src/main/java/org/hl7/davinci/endpoint/files/FileStore.java
server/src/main/java/org/hl7/davinci/endpoint/files/QuestionnaireValueSetProcessor.java
server/src/main/java/org/hl7/davinci/endpoint/files/cdsconnect/CdsConnectFileStore.java
server/src/main/java/org/hl7/davinci/endpoint/vsac/ValueSetCache.java

Stores the url fields of ValueSets when loaded and adds a way to search by the urls. This adds support for valuesets from other sources with canonical urls to be used as long as they can be pulled in to our CDS-Library repo.
Embeds referenced valuesets in questionnaires and provides an abstract class for doing generic modifications on FHIR resources.
An example of using this work with the HL7 FHIR administrative-gender valueset in the HOT questionnaire can be seen by using the `hot-valuesets-questionnaire` branch of CDS-Library.

714 - ValueSets in Questionnaires

---

server/src/main/java/org/hl7/davinci/endpoint/files/CommonFileStore.java
server/src/main/java/org/hl7/davinci/endpoint/files/FileStore.java
server/src/main/java/org/hl7/davinci/endpoint/files/SubQuestionnaireProcessor.java

Moves sub-questionnaire refactoring code out of CommonFileStore into it's own resource processor class.
Best tested with the Ventilator Order rule with `pat016`.

751- Sub-questionnaire refactor

---

server/build.gradle
server/src/main/java/org/hl7/davinci/endpoint/cql/CqlExecution.java
server/src/main/java/org/hl7/davinci/endpoint/cql/LocalLibraryLoader.java
server/src/main/java/org/hl7/davinci/endpoint/files/CDSLibrarySourceProvider.java
server/src/main/java/org/hl7/davinci/endpoint/files/cdsconnect/CdsConnectFileStore.java
server/src/main/java/org/hl7/davinci/endpoint/files/github/GitHubFileStore.java
server/src/main/java/org/hl7/davinci/endpoint/files/local/LocalFileStore.java
server/src/main/jib/rules/cms/cpt/95259/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/hcpcs/A0426/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/hcpcs/E0250/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/hcpcs/E0424/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/hcpcs/E0431/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/hcpcs/E0433/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/hcpcs/E0434/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/hcpcs/E0439/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/hcpcs/E0441/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/hcpcs/E0442/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/hcpcs/E0443/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/hcpcs/E0444/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/hcpcs/E0465/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/hcpcs/E0470/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/hcpcs/E0601/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/hcpcs/E1390/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/hcpcs/E1391/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/hcpcs/E1392/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/hcpcs/K0738/FHIRHelpers-4.0.0.cql
server/src/main/jib/rules/cms/rxnorm/860195/FHIRHelpers-4.0.0.cql
server/src/main/jib/smartAppFhirArtifacts/FHIRHelpers-4.0.0.cql
server/src/test/resources/CDS-Library/Shared/R4/files/FHIRHelpers-4.0.0.cql

Updates cql-to-elm to 1.4.9
Supports translating CQL libraries that reference other libraries.
For testing, HOT Order with William Oster. With CDS_Library branch `Shared_CQL_Library` and DTR `library-support-and-valueset-errors`.

DMEERX-754 Library translation support

---

server/src/main/java/org/hl7/davinci/endpoint/files/CDSLibrarySourceProvider.java

Without this change certain libraries cannot be retrieved on Linux.

Fix case sensitivity issue on FHIR version in CDS Library Source Provider

---

server/src/main/java/org/hl7/davinci/endpoint/files/CDSLibrarySourceProvider.java

Without this change retrieving some Library files on Linux fails.

Fix case sensitivity issue on FHIR version in CDS Library Source Provider.

---

server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
server/src/main/resources/application.yml

To be used with DTR's questionnaire url branch.  This makes CRD return the fhir/filepath in the appcontext.  It still send the `template`, which is the URI of the questionnaire, but it also send the base URL of the fhir server as `fhirpath` for use by the DTR app.  It also makes `filepath` work again, instead of just being a placeholder.  
These changes will likely need to be reflected in the IG.

Questionnaire url

---

.vscode/launch.json

the .vscode folder from the CRD repo (https://github.com/HL7-DaVinci/CRD/pull/266/files#diff-bd5430ee7c51dc892a67b3f2829d1f5b6d223f0fd48b82322cfd45baf9f5e945) that was used for debugging capabilities in the docker dev set up was removed. I had added that in as part of my docker dev set up, which allowed for running the entire drls + pas set up within docker containers along with the option to debug each server (add breakpoints and step through, etc.). That vscode configuration was a part of that (see: https://github.com/HL7-DaVinci/CRD/pull/264/files#diff-bd5430ee7c51dc892a67b3f2829d1f5b6d223f0fd48b82322cfd45baf9f5e945, which is the pr merged right before yours). This pr adds that file back into the repo

added debugger for docker configuration back

---

server/src/main/java/org/hl7/davinci/endpoint/files/LibraryContentProcessor.java
server/src/main/java/org/hl7/davinci/endpoint/files/github/GitHubFileStore.java

Make FHIR version all caps and make sure to read the stream only once when converting CQL to ELM.

Fix issues created recently with GitHub file retrieval. 

---

server/src/main/java/org/hl7/davinci/endpoint/files/LibraryContentProcessor.java

The fix is to get the path right with an uppercase 'R4' for the FHIR version.

Fix issue on docker where CQL files fail to be embedded in the Library.

---

resources/src/main/java/org/hl7/davinci/PrefetchTemplateElement.java
resources/src/main/java/org/hl7/davinci/r4/CrdRequestCreator.java
resources/src/main/java/org/hl7/davinci/r4/crdhook/CrdPrefetch.java
resources/src/main/java/org/hl7/davinci/r4/crdhook/orderselect/CrdPrefetchTemplateElements.java
resources/src/main/java/org/hl7/davinci/r4/crdhook/ordersign/CrdPrefetchTemplateElements.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/FhirBundleProcessor.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/FhirRequestProcessor.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderSelectService.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderSignService.java
server/src/main/java/org/hl7/davinci/endpoint/components/PrefetchHydrator.java
server/src/main/java/org/hl7/davinci/endpoint/fhir/r4/QuestionnairePackageOperation.java
server/src/test/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/EndToEndRequestPrefetchTest.java
server/src/test/resources/deviceRequestFullPrefetchWithCoverage_r4.json

This PR adds support for accepting multiple prefetch inputs from the request generator. It now meets the spec requirement of prefetch with the format: prefetch:{{deviceRequestBundle: ...},{coverageBundle: ...}, ...}. It supports coverages as a separate bundle in the prefetch.
Updates were also made to the FhirBundleProcessor (in processDeviceRequests(), processServiceRequests(), etc) so that they now properly extract the patient resource itself from the prefetch, not from the request's references. It also implemented structural support for using the coverage bundle, though that will need to be expanded in future to better utilize the coverage resources.
This PR also updated all of the prefetch templates to the newest versions with support for coverage bundle prefethes.
It updated the …

Add Support For Multiple Prefetch and Updated Prefetch Templates

---

server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/FhirRequestProcessor.java
server/src/main/java/org/hl7/davinci/endpoint/components/QueryBatchRequest.java

This PR fixes two bugs with the Query Batch Request:
1. If there were any resources missing that should have been prefetched, the QBR would add a duplicate of the main request resources.
2. The QBR would only look at the first element of the draft orders, meaning that the QBR's requests would be flattened into the first prefetch bundle, rather than being inserted into the correct associated bundles.

Query Batch Request Bug Fixes

---

server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/FhirBundleProcessor.java
server/src/main/java/org/hl7/davinci/endpoint/controllers/FhirController.java
server/src/main/java/org/hl7/davinci/endpoint/fhir/r4/QuestionnairePackageOperation.java
server/src/main/java/org/hl7/davinci/endpoint/files/CommonFileStore.java

These changes are usable with DTR app context changes.  This doesn't really have much to do with relaunching other than modification of the Questionnaire operation to function properly when given an ID parameter.  
To test these changes, you can check the app context when loading DTR to find that it is conformant to the new IG standard, removing filepath and fhirpath and introducing coverage/response.  
Overall the major changes are:
- Modification of the smartLinkBuilder to produce the new appContext (CdsService)
- The introduction of an ID specific questionnaire-package endpoint to handle that case (FhirController) 
- Modification of the questionnaire-package operation to work with ID specific requests (QuestionnairePackageOperation)

App context changes

---

server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/FhirBundleProcessor.java
server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderSignService.java

This PR adds support for passing coverages to the CQL rules for the rules to use to determine coverage eligibility.
To test: William Oster has Medicare Part A and Teddy Roosevelt has Part B. The example CQL rule adds a condition to HomeOxygenTherapy'sRULE_APPLIES that the coverage must be Medicare Part A. Thus, for William Oster Home Oxygen Therapy should return the expected cards but for Teddy Roosevelt it should return "No Documentation Rules Found"
Use with branches:
- test-ehr: coverage-rules https://github.com/HL7-DaVinci/test-ehr/pull/65
- CDS-Library: coverage rules https://github.com/HL7-DaVinci/CDS-Library/pull/92

Added support for passing coverage to CQL rules
