HL7-DaVinci/CRD

- server/device_request.json
- server/src/main/java/endpoint/cdshooks/models/Action.java
- server/src/main/java/endpoint/cdshooks/models/Card.java
- server/src/main/java/endpoint/cdshooks/models/CdsRequest.java
- server/src/main/java/endpoint/cdshooks/models/CdsResponse.java
- server/src/main/java/endpoint/cdshooks/models/CdsService.java
- server/src/main/java/endpoint/cdshooks/models/CdsServiceInformation.java
- server/src/main/java/endpoint/cdshooks/models/Hook.java
- server/src/main/java/endpoint/cdshooks/models/Link.java
- server/src/main/java/endpoint/cdshooks/models/Prefetch.java
- server/src/main/java/endpoint/cdshooks/models/Source.java
- server/src/main/java/endpoint/cdshooks/models/Suggestion.java
- server/src/main/java/endpoint/cdshooks/services/crd/CrdCdsRequest.java
- server/src/main/java/endpoint/cdshooks/services/crd/CrdCdsService.java
- server/src/main/java/endpoint/cdshooks/services/crd/OrderReviewContext.java
- server/src/main/java/endpoint/components/FhirComponents.java
- server/src/main/java/endpoint/controllers/CdsHooksController.java
Add an initial version of the CDS Hook order-review endpoint, which includes adding many CDS models (partly adapted from the swagger ones). Should respond to posts to http://localhost:8080/cds-services/coverage-requirements-discovery.
> CDS endpoint

- config/checkstyle/checkstyle.xml
- creator/src/main/java/org/hl7/davinci/creator/RequestWriter.java
- resources/src/main/java/org/hl7/davinci/cdshooks/CdsRequest.java
- resources/src/test/java/org/hl7/davinci/cdshooks/orderreview/CrdCdsRequestTest.java
- resources/src/test/resources/org/hl7/davinci/cdshooks/orderreview/request.json
- server/src/main/java/endpoint/cdshooks/services/crd/CrdCdsService.java
- server/src/main/java/endpoint/components/CardBuilder.java
- server/src/test/java/endpoint/cdshooks/components/CardBuilderTest.java
- server/src/test/java/endpoint/cdshooks/services/crd/CrdCdsServiceTest.java
- testingClient/src/main/java/TestClient.java
Combines with previous PR which I will now close.
Better testing and tweaking of the checkstyle rules.
CardBuilder for CDS Hooks responses with a new hardcoded response from our service.
> Card builder and unit tests

- creator/src/main/java/org/hl7/davinci/creator/RequestWriter.java
- resources/src/main/java/org/hl7/davinci/CrdRequestCreator.java
- resources/src/main/java/org/hl7/davinci/cdshooks/CrdPrefetch.java
- resources/src/main/java/org/hl7/davinci/cdshooks/Hook.java
- resources/src/main/java/org/hl7/davinci/cdshooks/medicationprescribe/MedicationPrescribeContext.java
- resources/src/main/java/org/hl7/davinci/cdshooks/medicationprescribe/MedicationPrescribeRequest.java
- resources/src/main/java/org/hl7/davinci/cdshooks/orderreview/OrderReviewRequest.java
- resources/src/test/java/org/hl7/davinci/cdshooks/orderreview/OrderReviewRequestTest.java
- server/src/main/java/endpoint/cdshooks/services/crd/CrdCdsService.java
- server/src/main/java/endpoint/controllers/CdsHooksController.java
- server/src/test/java/endpoint/cdshooks/services/crd/CrdCdsServiceTest.java
- testingClient/src/main/java/TestClient.java
Building the resources to represent a medication-prescribe CDS Hook
request. This caused some minor refactoring of the resources to
represent order-review.
> Creating the resource for medication-prescribe

- server/src/main/java/org/hl7/davinci/endpoint/controllers/CdsHooksController.java
- server/src/test/java/endpoint/cdshooks/services/crd/ServicesDiscoveryEndpointTest.java
This adds the service discovery endpoint and a test.
> added services discovery endpoint and test

- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/MedicationPrescribeService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/OrderReviewService.java
> added prefetch templates

- request-generator/package-lock.json
- request-generator/package.json
- request-generator/src/components/CheckBox.js
- request-generator/src/components/ConsoleBox.js
- request-generator/src/components/consoleBox.css
- request-generator/src/containers/RequestBuilder.js
- request-generator/src/index.css
Basically just swallows errors and outputs to the little console box that something went wrong.  Not every response comes back as the error, many times the error occurs and the only thing that is caught is a `TypeError` declaring that it's unable to fetch, no status code or error message is given back, even though the error gets logged to the actual console, it doesn't seem possible to catch that error and output its status code.  In these cases a generic error message is put out.  This might include something like putting in the wrong client id. 
Also this gets rid of the extra card being added into cards to be shown.
> Better error

- examples/request.json
- request-generator/src/containers/RequestBuilder.js
- resources/src/main/java/org/hl7/davinci/CrdRequestCreator.java
- resources/src/main/java/org/hl7/davinci/cdshooks/orderreview/OrderReviewRequest.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/OrderReviewService.java
- server/src/test/java/org/hl7/davinci/endpoint/cdshooks/services/crd/OrderReviewServiceTest.java
* Updated our sample request to have the correct prefetch structure
* Updated RequestBuilder to generate the correct prefetch
* Fixed serialization of OrderReviewRequest
* OrderReviewService now checks the prefetch bundle for a patient
* OrderReviewServiceTest has been re-enabled
> Updates to fix prefetch generation

- request-generator/src/components/ConsoleBox.js
- request-generator/src/components/consoleBox.css
- server/src/main/java/org/hl7/davinci/endpoint/SecurityConfig.java
the security still exists it just doesn't protect any endpoints.
> removed keyCloak protection

- server/src/main/java/org/hl7/davinci/endpoint/controllers/r4/CdsHooksController.java
- server/src/test/java/org/hl7/davinci/endpoint/cdshooks/services/crd/EndToEndRequestPrefetchTest.java
This updates the service endpoint urls to include /r4.
> updated service endpoints urls for r4

- server/src/main/java/org/hl7/davinci/endpoint/CoverageRequirementsDiscoveryOperation.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderReviewService.java
- server/src/main/java/org/hl7/davinci/endpoint/database/CoverageRequirementRuleFinder.java
- server/src/main/java/org/hl7/davinci/endpoint/database/DataRepository.java
Before, server would only look at the code regardless of system. Now the
finder uses code and code system to find the correct rule.
> Matching codes now also uses code system

- creator/src/main/java/org/hl7/davinci/creator/RequestWriter.java
- resources/src/main/java/org/hl7/davinci/CrdRequestCreator.java
- resources/src/main/java/org/hl7/davinci/cdshooks/medicationprescribe/MedicationPrescribeRequest.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/MedicationPrescribeService.java
- server/src/main/resources/data.sql
- server/src/test/java/org/hl7/davinci/endpoint/cdshooks/services/crd/MedicationPrescribeServiceTest.java
- testingClient/src/main/java/org/hl7/davinci/testClient/TestClient.java
Modified CrdRequestCreator so that it now creates requests for
order-review and medication-prescribe. Tried to reuse as much code as
possible.
Adds two medications to our start up data set.
> Hooking MedicationPrescribeService up to the DB

- Procfile
This adds a Procfile, which is what heroku uses to run our application.
> Adding Procfile for heroku

- resources/src/main/java/org/hl7/davinci/stu3/FhirComponents.java
- resources/src/main/java/org/hl7/davinci/stu3/fhirresources/DaVinciDeviceRequest.java
- resources/src/main/java/org/hl7/davinci/stu3/fhirresources/DaVinciMedicationRequest.java
- resources/src/test/resources/org/hl7/davinci/stu3/crdhook/orderreview/requestWithHydratedPrefetchBundle.json
- server/src/test/resources/deviceRequestEmptyPrefetch_stu3.json
- server/src/test/resources/deviceRequestPrefetchResponse_stu3.json
This PR updates the profile URLs to their actual values.
> updated profile urls

- request-generator/src/components/CheckBox.js
- request-generator/src/containers/RequestBuilder.js
You can now turn on and off a populated prefetch from the
request-generator user interface
> Adding checkbox for prefetch

- server/src/main/resources/data.sql
- server/src/test/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/EndToEndRequesMultipleCardsTest.java
- server/src/test/resources/deviceRequestFullPrefetch_r4.json
Functionality already existed for returning multiple cards, this just adds a test.
> added test for returning multiple cards from server

- request-generator/src/containers/RequestBuilder.js
- resources/src/main/java/org/cdshooks/CdsRequest.java
- resources/src/main/java/org/cdshooks/FhirAuthorization.java
- resources/src/test/resources/org/hl7/davinci/r4/crdhook/orderreview/requestWithHydratedPrefetchBundle.json
- resources/src/test/resources/org/hl7/davinci/stu3/crdhook/orderreview/requestWithHydratedPrefetchBundle.json
- server/src/main/java/org/hl7/davinci/endpoint/components/PrefetchHydrator.java
Making an object to hold the fhirAuthorization
Fixing the property name
Fixes to the request-generator to bring it in line with changes in the ehr-server
> Fixes to use OAuth when fetching resources

- ehr-server/build.gradle
- ehr-server/src/main/resources/data/1. practitioner.json
- ehr-server/src/main/resources/data/2. organization.json
- ehr-server/src/main/resources/data/3. coverage.json
- ehr-server/src/main/resources/data/4. location.json
- ehr-server/src/main/resources/data/5. patient.json
- ehr-server/src/main/resources/data/6. practitioner-role.json
- ehr-server/src/main/resources/data/7. device-request.json
- request-generator/src/containers/RequestBuilder.js
- server/src/main/java/org/hl7/davinci/endpoint/components/PrefetchHydrator.java
This PR adds a gradle task to load data into the ehr server. Note that currently the ehr server db is persistent so the script doesn't need to be run constantly. Note also it will overwrite existing resources with the same type and id if they already exist.
> finished script to load data into ehr server

- ehr-server/README.md
- ehr-server/src/main/java/org/hl7/davinci/ehrServer/FhirTesterConfig.java
- ehr-server/src/main/java/org/hl7/davinci/ehrServer/requestGenerator/RequestGeneratorController.java
- ehr-server/src/main/java/org/hl7/davinci/ehrServer/requestGenerator/RequestGeneratorMvcConfig.java
- ehr-server/src/main/webapp/WEB-INF/reqgen
- ehr-server/src/main/webapp/WEB-INF/web.xml
- request-generator/README.md
- request-generator/package-lock.json
- request-generator/package.json
Set up EHR FHIR Server (ehr-server) so that it hosts the request-generator app.
> Set up EHR FHIR Server so that it hosts the request-generator

- resources/src/main/java/org/hl7/davinci/r4/Utilities.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderReviewService.java
Fixed merge conflicts from previous PR.  Adds service request to the r4 service.
> redid service request addition to reflect changes to CdsService

- README.md
- ehr-server/README.md
- server/src/main/publickey_interface/package-lock.json
- server/src/main/request_logging/package-lock.json
updates the readme's and fixes the dependency github is flagging as vulnerable.
> Read me and security

- examples/r4/order-review/documentation-required/request.json
- resources/src/main/java/org/hl7/davinci/r4/Utilities.java
- resources/src/main/java/org/hl7/davinci/stu3/Utilities.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/MedicationPrescribeService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderReviewService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/stu3/MedicationPrescribeService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/stu3/OrderReviewService.java
These small changes fix the issue of patient ID being incorrect creating a null pointer and removes the catch of generic `exception` in the utilities and service classes.
> Medication request subject fix

- server/src/main/java/org/hl7/davinci/endpoint/components/CardBuilder.java
- server/src/main/java/org/hl7/davinci/endpoint/database/CoverageRequirementRule.java
- server/src/main/resources/data.sql
- server/src/main/resources/node_interfaces/src/components/TableRow.js
- server/src/test/java/ServerTest.java
- server/src/test/java/org/hl7/davinci/endpoint/cdshooks/components/CardBuilderTest.java
there might be a change or two needed in other locations that use the data model, but everything looks to work alright.
> changed no_auth_needed to auth_required

- examples/r4/medication-prescribe/documentation-required/request.json
- examples/r4/medication-prescribe/no-documentation-rules/request.json
- examples/r4/order-review/documentation-required/request.json
- examples/r4/order-review/documentation-required/request_no_prefetch.json
- examples/r4/order-review/no-documentation-rules/request.json
- resources/src/main/java/org/hl7/davinci/r4/crdhook/CrdPrefetchTemplateElements.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/MedicationPrescribeService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderReviewService.java
Fixes some issues with the example requests and fixes an issue with the prefetch template that would cause medication prescribe requests to not get practitioner role/location from a fhir server.
> Scenario testing

- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
- server/src/main/java/org/hl7/davinci/endpoint/database/RequestLog.java
Just some housekeeping moving clutter from CDS service into Request Log.
> [DME199] cleaned up request log

- server/src/main/resources/data.sql
This adds a rule to the server to cover oxygen therapy for the demo in
the Interop Showcase.
> [216] Adding the code to be used at HIMSS19

- server/README.md
- server/src/main/java/org/hl7/davinci/endpoint/Utils.java
- server/src/main/java/org/hl7/davinci/endpoint/YamlConfig.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
- server/src/main/java/org/hl7/davinci/endpoint/components/CardBuilder.java
- server/src/main/java/org/hl7/davinci/endpoint/controllers/r4/CdsHooksController.java
- server/src/main/java/org/hl7/davinci/endpoint/controllers/stu3/CdsHooksController.java
- server/src/main/jib/rules/cms/hcpcs/E0424/E0424.cql
- server/src/main/jib/rules/cms/hcpcs/E0424_2/E0424_2.cql
- server/src/main/resources/application.yml
- server/src/test/java/org/hl7/davinci/endpoint/cdshooks/components/CardBuilderTest.java
- server/src/test/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/MedicationPrescribeServiceTest.java
- server/src/test/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderReviewServiceTest.java
- server/src/test/java/org/hl7/davinci/endpoint/cdshooks/services/crd/stu3/MedicationPrescribeServiceTest.java
- server/src/test/java/org/hl7/davinci/endpoint/cdshooks/services/crd/stu3/OrderReviewServiceTest.java
- server/src/test/resources/application.yml
Merging cole's unfinished changes with the main smart app launching branch
> Return smart link

- ehr-server/fhirResourcesToLoad/o2billy_01__patient.json
- ehr-server/fhirResourcesToLoad/o2billy_02__coverage.json
- ehr-server/fhirResourcesToLoad/o2billy_03__condition.json
- ehr-server/fhirResourcesToLoad/o2billy_03__conditionB.json
- ehr-server/fhirResourcesToLoad/o2billy_03__conditionC.json
- ehr-server/fhirResourcesToLoad/o2billy_03__observation.json
- ehr-server/fhirResourcesToLoad/o2billy_03__observationB.json
- ehr-server/fhirResourcesToLoad/o2billy_04__device-request.json
- ehr-server/fhirResourcesToLoad/o2jane_01__patient.json
- ehr-server/fhirResourcesToLoad/o2jane_02__coverage.json
- ehr-server/fhirResourcesToLoad/o2jane_03__condition.json
- ehr-server/fhirResourcesToLoad/o2jane_03__conditionB.json
- ehr-server/fhirResourcesToLoad/o2jane_03__conditionC.json
- ehr-server/fhirResourcesToLoad/o2jane_03__observation.json
- ehr-server/fhirResourcesToLoad/o2jane_03__observationB.json
- ehr-server/fhirResourcesToLoad/o2jane_04__device-request.json
- ehr-server/fhirResourcesToLoad/o2teddy_01__patient.json
- ehr-server/fhirResourcesToLoad/o2teddy_02__coverage.json
- ehr-server/fhirResourcesToLoad/o2teddy_03__condition.json
- ehr-server/fhirResourcesToLoad/o2teddy_03__conditionB.json
- ehr-server/fhirResourcesToLoad/o2teddy_03__conditionC.json
- ehr-server/fhirResourcesToLoad/o2teddy_03__observation.json
- ehr-server/fhirResourcesToLoad/o2teddy_03__observationB.json
- ehr-server/fhirResourcesToLoad/o2teddy_04__practitioner.json
- ehr-server/fhirResourcesToLoad/o2teddy_05__device-request.json
Add Teddy
Add Billy
Added Jane.
> [272] Create new test patients

- ehr-server/src/main/java/org/hl7/davinci/ehrserver/authproxy/AppContext.java
- ehr-server/src/main/java/org/hl7/davinci/ehrserver/authproxy/Payload.java
- ehr-server/src/main/java/org/hl7/davinci/ehrserver/authproxy/PayloadDAOImpl.java
- ehr-server/src/main/java/org/hl7/davinci/ehrserver/authproxy/PayloadMapper.java
- server/src/main/java/org/hl7/davinci/endpoint/YamlConfig.java
- server/src/main/java/org/hl7/davinci/endpoint/cdsconnect/CdsConnectRuleFinder.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/MedicationPrescribeService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderReviewService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/stu3/MedicationPrescribeService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/stu3/OrderReviewService.java
- server/src/main/java/org/hl7/davinci/endpoint/database/CoverageRequirementRuleDownloaderDatabase.java
- server/src/main/java/org/hl7/davinci/endpoint/rules/CoverageRequirementRuleCriteria.java
- server/src/main/java/org/hl7/davinci/endpoint/rules/CoverageRequirementRuleResult.java
- server/src/main/resources/application.yml
Add support for passing the filepath with the appContext so that DTR can request files through the getfiles endpoint. This is needed for file retrieval from CDS Connect.
> Changes to support file retrieval from CDS Connect

- README.md
- ehr-server/README.md
A few improvements that may help clear up some confusion when getting started.
> Readme Improvements for Keycloak and ehr-server load data

- ehr-server/fhirResourcesToLoad/5. patient.json
- ehr-server/fhirResourcesToLoad/7. device-request.json
- ehr-server/fhirResourcesToLoad/o2billy_01__patient.json
- ehr-server/fhirResourcesToLoad/o2billy_02__coverage.json
- ehr-server/fhirResourcesToLoad/o2billy_02__organization.json
- ehr-server/fhirResourcesToLoad/o2jane_01__patient.json
- ehr-server/fhirResourcesToLoad/o2jane_02__coverage.json
- ehr-server/fhirResourcesToLoad/o2jane_02__organization.json
- ehr-server/fhirResourcesToLoad/o2john_01__patient.json
- ehr-server/fhirResourcesToLoad/o2john_02__coverage.json
- ehr-server/fhirResourcesToLoad/o2john_02__organization.json
- ehr-server/fhirResourcesToLoad/o2john_04__device-requestB.json
- ehr-server/fhirResourcesToLoad/o2teddy_01__patient.json
- ehr-server/fhirResourcesToLoad/o2teddy_02__coverage.json
- ehr-server/fhirResourcesToLoad/o2teddy_02__organization.json
- server/src/main/java/org/hl7/davinci/endpoint/components/CardBuilder.java
Update CardBuilder::setRuleApplies to handle null values.
> Update FHIR Resources with missing data. 

- .gitignore
- README.md
- ehr-server/src/main/resources/fhirServer.properties
I corrected some minor typos in the KeyCloak section.
> Readme "Setting for KeyCloak"

- server/src/main/jib/rules/cms/cpt/95259/95259-r4.cql
- server/src/main/jib/rules/cms/cpt/95259/95259.cql
- server/src/main/jib/rules/cms/cpt/95259/FHIRHelpers-4.0.0.cql
- server/src/main/jib/smartAppFhirArtifacts/BasicPatientInfoPrepopulate-R4.cql
- server/src/main/jib/smartAppFhirArtifacts/BloodGlucosePrepopulation.cql
- server/src/main/jib/smartAppFhirArtifacts/FHIRHelpers-4.0.0.cql
- server/src/main/jib/smartAppFhirArtifacts/PositiveAirwayPressurePrepopulate.cql
- server/src/main/jib/smartAppFhirArtifacts/home-blood-glucose-questionnaire.json
- server/src/main/jib/smartAppFhirArtifacts/library-basic-patient-info-prepopulate-r4.json
- server/src/main/jib/smartAppFhirArtifacts/library-blood-glucose-prepopulate.json
- server/src/main/jib/smartAppFhirArtifacts/library-fhir-helpers-r4.json
Started scaffolding of Home Glucose Monitor questionnaire and prepopulation.
> Start of Home Glucose Monitor DTR questionnaire and prepopulation rules

- server/src/main/jib/rules/cms/hcpcs/E0424/E0424-r4.cql
- server/src/main/jib/smartAppFhirArtifacts/OxygenTherapyPrepopulation-R4.cql
- server/src/main/jib/smartAppFhirArtifacts/home-oxygen-questionnaire_2-r4.json
- server/src/main/jib/smartAppFhirArtifacts/library-oxygen-therapy-prepopulate-r4.json
Needs updated condition codes in test data for this to properly operate. https://github.com/HL7-DaVinci/test-ehr/pull/4
> FHIR R4 version of oxygen therapy

- server/src/main/jib/smartAppFhirArtifacts/OxygenTherapyPrepopulation.cql
This is a workaround to a cql-execution bug
> added null check on DeviceRequest.intent

- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
- server/src/main/java/org/hl7/davinci/endpoint/components/CardBuilder.java
Add codes handling ProgressNoteUrl
> 591 Ventilator Progress Note

- server/src/main/java/org/hl7/davinci/endpoint/Utils.java
- server/src/main/java/org/hl7/davinci/endpoint/controllers/DataController.java
Update inserted link to work through a proxied web server.
> [729] Get new DRLS branch working with Logica Health - Connectathon

- server/src/main/java/org/hl7/davinci/endpoint/controllers/r4/CdsHooksController.java
- server/src/main/java/org/hl7/davinci/endpoint/controllers/stu3/CdsHooksController.java
Added order-sign and order-select to capability statement
> DMEERX-739 - update capability statement for order-sign and order-select

- server/src/main/java/org/hl7/davinci/endpoint/controllers/DataController.java
- server/src/main/java/org/hl7/davinci/endpoint/files/CommonFileStore.java
1) Add ?url={url} query parameter
2) Save Library.url and Questionnaire.url during initial loading
> 737-add-url-query-parameter

- server/src/main/java/org/hl7/davinci/endpoint/files/CommonFileStore.java
- server/src/main/resources/application.yml
This PR fixes some bugs in sub-questionnaire processing after cqf library changes:
1) Added capability to import more than one root items from sub questionnaire.
2) Fix bugs in comparing Extensions related to cqf canonical url
> Fix Extension comparasion

- server/src/main/java/org/hl7/davinci/endpoint/files/QuestionnaireValueSetProcessor.java
Move the contained valueset reference from initial element to extension element.
> Change contained ValueSet reference from initial to extension

- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
- server/src/main/java/org/hl7/davinci/endpoint/components/CardBuilder.java
This PR updates CRD to handle care plan form.
> DMEERX-567 DTR rule set for Plan of Care For Home Health Service

- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
- server/src/main/java/org/hl7/davinci/endpoint/components/CardBuilder.java
Add rules and links for PA Request
> Add rules for PA request

- resources/src/main/java/org/hl7/davinci/FhirResourceInfo.java
- resources/src/main/java/org/hl7/davinci/SuppressParserErrorHandler.java
- resources/src/main/java/org/hl7/davinci/r4/Utilities.java
- resources/src/main/java/org/hl7/davinci/stu3/Utilities.java
- server/src/main/java/org/hl7/davinci/endpoint/controllers/FhirController.java
- server/src/main/java/org/hl7/davinci/endpoint/database/FhirResource.java
- server/src/main/java/org/hl7/davinci/endpoint/fhir/r4/Metadata.java
- server/src/main/java/org/hl7/davinci/endpoint/fhir/stu3/Metadata.java
- server/src/main/java/org/hl7/davinci/endpoint/files/CommonFileStore.java
- server/src/main/java/org/hl7/davinci/endpoint/files/SubQuestionnaireProcessor.java
- server/src/main/java/org/hl7/davinci/endpoint/files/cdsconnect/CdsConnectFileStore.java
- server/src/main/java/org/hl7/davinci/endpoint/files/github/GitHubFileStore.java
- server/src/main/java/org/hl7/davinci/endpoint/files/local/LocalFileStore.java
- server/src/main/java/org/hl7/davinci/endpoint/vsac/ValueSetCache.java
[397] Send QuestionnaireResponse to Payer as requested.
> [397] Send QuesionnaireResponse to payer.

- server/src/main/java/org/hl7/davinci/endpoint/files/SubQuestionnaireProcessor.java
Add sub-qustionnaire-expand extension
> add sub-questionnaire-expand extension

- SetupGuideForMacOS.md
Created complete MacOS setup guide for DRLS. 
Few notes:
- The only "modified" file in this pull request is a single new file: SetupGuideForMacOS.md
- A Windows setup guide is partially done but is not yet ready to be included.
- Have details on networking configurations drafted, but didn't include in this pull request.
> Development environment setup guide (macos)

- build.gradle
- resources/src/main/java/org/hl7/ShortNameMaps.java
- server/src/main/java/org/hl7/davinci/endpoint/files/CommonFileStore.java
The changes in this PR meet the requirement to load Mettles Solution rule set.
> DMEERX-794 Mettles Solution Rule Set

- server/src/main/java/org/hl7/davinci/endpoint/config/GitHubConfig.java
- server/src/main/java/org/hl7/davinci/endpoint/config/LocalDb.java
- server/src/main/java/org/hl7/davinci/endpoint/files/CommonFileStore.java
- server/src/main/java/org/hl7/davinci/endpoint/files/github/GitHubConnection.java
- server/src/main/java/org/hl7/davinci/endpoint/files/github/GitHubFileStore.java
- server/src/main/java/org/hl7/davinci/endpoint/files/local/LocalFileStore.java
- server/src/main/java/org/hl7/davinci/endpoint/vsac/ValueSetCache.java
- server/src/main/resources/application.yml
- server/src/test/resources/application.yml
Support for putting most of the rule sets into a folder within the CDS Library as well as moving the rule sets not created as part of the reference implementation into a different folder.
> CDS Library Reorganization

- server/src/main/java/org/hl7/davinci/endpoint/SecurityConfig.java
- server/src/main/resources/application.yml
Originally thought we needed some bigger changes to our JWT filter due to some errors I was seeing but it turns out I just had the Spring magic wrong.
> remove extra code

- resources/src/main/java/org/hl7/ShortNameMaps.java
- server/src/main/java/org/hl7/davinci/endpoint/controllers/FhirController.java
- server/src/main/java/org/hl7/davinci/endpoint/database/RequestLog.java
- server/src/main/java/org/hl7/davinci/endpoint/files/QuestionnaireValueSetProcessor.java
This PR modifies CRD for make Mettles rule sets work. 
To test, use test-ehr and CDS-Libary prosrule branches.
> DMEERX-794 Validate Mettles Rule Sets

- server/src/main/java/org/hl7/davinci/endpoint/SecurityConfig.java
- server/src/main/java/org/hl7/davinci/endpoint/config/YamlConfig.java
- server/src/main/java/org/hl7/davinci/endpoint/controllers/r4/CdsHooksController.java
- server/src/main/resources/application.yml
- server/src/test/resources/application.yml
Update CORS Security Configuration to read values from the configuration file or environment variables.
> Update CORS Security Configuration

- gradle/wrapper/gradle-wrapper.properties
- operations/build.gradle
- resources/build.gradle
- server/build.gradle
switches gradle to newest version.  Compatible with Java 16.  Tested with openjdk11, needs some extra testing with openjdk8.
> Update gradle to newest version

- resources/src/main/java/org/cdshooks/Action.java
- resources/src/main/java/org/cdshooks/ActionSerializer.java
- resources/src/main/java/org/cdshooks/Card.java
- resources/src/main/java/org/cdshooks/CoverageRequirements.java
- resources/src/main/java/org/cdshooks/Suggestion.java
- resources/src/main/java/org/hl7/davinci/r4/Utilities.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/FhirRequestProcessor.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderSignService.java
- server/src/main/java/org/hl7/davinci/endpoint/components/CardBuilder.java
- server/src/main/java/org/hl7/davinci/endpoint/database/FhirResourceCriteria.java
- server/src/main/java/org/hl7/davinci/endpoint/database/FhirResourceRepository.java
- server/src/main/java/org/hl7/davinci/endpoint/files/CommonFileStore.java
- server/src/main/java/org/hl7/davinci/endpoint/rules/CoverageRequirementRuleCriteria.java
Add support for preemptive prior auth.
To test you must include the changes for the crd-request-generator in the preemptive-prior-auth branch as well as the CDS-Library in the preemptive-prior-auth branch. Choose Theodor Roosevelt and G0180 Service Request for Medicare-covered home health services under a home health plan of care.
> Preemptive prior auth

- resources/src/main/java/org/hl7/davinci/r4/Utilities.java
- server/src/main/java/org/hl7/davinci/endpoint/components/PrefetchHydrator.java
Fix issues with PrefetchHydrator to handle cases with empty prefetch provided in hook.
Issue was found while trying to test prefetch during connectathon.
> Fix issues with PrefetchHydrator 

- resources/src/main/java/org/cdshooks/Coding.java
- resources/src/main/java/org/cdshooks/Source.java
- resources/src/main/java/org/hl7/davinci/r4/CardTypes.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
- server/src/main/java/org/hl7/davinci/endpoint/components/CardBuilder.java
- server/src/test/java/org/hl7/davinci/endpoint/cdshooks/components/CardBuilderTest.java
STU2 support for card types.
Test in conjunction with card-type branch of the crd-request-generator.
> Return the card type in the card source.

- resources/src/main/java/org/hl7/davinci/r4/Utilities.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/FhirBundleProcessor.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/FhirRequestProcessor.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderSelectService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderSignService.java
- server/src/main/java/org/hl7/davinci/endpoint/controllers/FhirController.java
- server/src/main/java/org/hl7/davinci/endpoint/database/FhirResourceCriteria.java
- server/src/main/java/org/hl7/davinci/endpoint/database/FhirResourceRepository.java
- server/src/main/java/org/hl7/davinci/endpoint/fhir/r4/Metadata.java
- server/src/main/java/org/hl7/davinci/endpoint/fhir/r4/QuestionnaireForOrderOperation.java
- server/src/main/java/org/hl7/davinci/endpoint/fhir/r4/QuestionnairePackageOperation.java
- server/src/main/java/org/hl7/davinci/endpoint/files/CommonFileStore.java
- server/src/main/java/org/hl7/davinci/endpoint/files/FileStore.java
- server/src/main/resources/application.yml
Add a Questionnaire-package operation to the Payer FHIR Server portion of CRD. This supports the DTR relaunch detailed in the DTR STU1.1 IG. Please note that this is not part of the CRD IG and is only included in CRD because CRD is also acting as the Payer FHIR Server to support DTR.
> Questionnaire-package to support DTR relaunch

- resources/src/main/java/org/cdshooks/Card.java
- resources/src/main/java/org/cdshooks/CardExtension.java
- resources/src/main/java/org/hl7/davinci/r4/Utilities.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderSelectService.java
- server/src/main/java/org/hl7/davinci/endpoint/components/CardBuilder.java
Add the davinci-associated-resource extension to the card containing a reference to the resource that the card is in response to.
To test, look at the output card and verify that there is an extension with a reference to the associated resource.
> STU1.1 Linking Cards to Requests

- resources/src/main/java/org/cdshooks/Card.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/FhirBundleProcessor.java
- server/src/main/java/org/hl7/davinci/endpoint/components/CardBuilder.java
- server/src/main/java/org/hl7/davinci/endpoint/rules/CoverageRequirementRuleResult.java
- server/src/test/java/org/hl7/davinci/endpoint/cdshooks/components/CardBuilderTest.java
Test this using the crd-request-generator changes within the phi branch.
> Add checking for PHI within deidentified Patient and Coverage Resources.

- resources/src/main/java/org/cdshooks/Configuration.java
- resources/src/main/java/org/cdshooks/CoverageRequirements.java
- resources/src/main/java/org/hl7/davinci/r4/crdhook/ConfigurationOption.java
- resources/src/main/java/org/hl7/davinci/r4/crdhook/orderselect/CrdExtensionConfigurationOptions.java
- resources/src/main/java/org/hl7/davinci/r4/crdhook/ordersign/CrdExtensionConfigurationOptions.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderSelectService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderSignService.java
Added card visibility configurations for the following:
- dtr-clin
- prior-auth
- coverage
Added a "max-cards" returned configuration. It is currently defaulted to 10.
> Added additional card configurations

- resources/src/main/java/org/hl7/davinci/r4/JacksonIBaseResourceDeserializer.java
- resources/src/main/java/org/hl7/davinci/r4/crdhook/CrdPrefetch.java
- resources/src/test/java/org/hl7/davinci/r4/crdhook/ordersign/OrderSignRequestTest.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/FhirRequestProcessor.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderSelectService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderSignService.java
- server/src/main/java/org/hl7/davinci/endpoint/components/PrefetchHydrator.java
Defined in the CDS Hook spec, the CDS Server prefetch should also accept OperationOutcomes. https://cds-hooks.org/specification/current/#prefetch-template. Changes have been made to accept Bundles and OperationOutcomes.
> Prefetch OperationOutcome support

- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/AppointmentBookService.java
I added functionality to the TODOs in the AppointmentBookService
> CFRID-330: Make sure Appointment-book hook is supported

- server/src/main/java/org/hl7/davinci/endpoint/fhir/r4/QuestionnairePackageOperation.java
- server/src/main/java/org/hl7/davinci/endpoint/files/QuestionnaireEmbeddedCQLProcessor.java
I added the context, intendedUse, and informationOrigin extensions to the Questionair response
> CFRID-572: Automated CQL-Based Answers Population

- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderSignService.java
- server/src/main/java/org/hl7/davinci/endpoint/components/QueryBatchRequest.java
I modified the code to remove the cards from response and added in system actions with appointment book resources
> CFRID-786: CDS Hooks Server – Appointment-Book Response

- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/AppointmentBookService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderDispatchService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderSelectService.java
- server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/r4/OrderSignService.java
- server/src/main/java/org/hl7/davinci/endpoint/components/QueryBatchRequest.java
Populated system actions for Order Discharge and cleaned up the code
> CFRID-791: CDS Hooks Server – Order-Dispatch Response
